// Generated by gencpp from file encoder_msgs/Encoder.msg
// DO NOT EDIT!


#ifndef ENCODER_MSGS_MESSAGE_ENCODER_H
#define ENCODER_MSGS_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace encoder_msgs
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : time_stamp(0.0)
    , left_encoder_count(0)
    , right_encoder_count(0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : time_stamp(0.0)
    , left_encoder_count(0)
    , right_encoder_count(0)  {
  (void)_alloc;
    }



   typedef float _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef int64_t _left_encoder_count_type;
  _left_encoder_count_type left_encoder_count;

   typedef int64_t _right_encoder_count_type;
  _right_encoder_count_type right_encoder_count;





  typedef boost::shared_ptr< ::encoder_msgs::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::encoder_msgs::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::encoder_msgs::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::encoder_msgs::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::encoder_msgs::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::encoder_msgs::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::encoder_msgs::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace encoder_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'encoder_msgs': ['/home/bill/bill_ros/bill_ws/src/encoder_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::encoder_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::encoder_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::encoder_msgs::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::encoder_msgs::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::encoder_msgs::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::encoder_msgs::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::encoder_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b66af2928dcdc45aac405392cc8c0f5c";
  }

  static const char* value(const ::encoder_msgs::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb66af2928dcdc45aULL;
  static const uint64_t static_value2 = 0xac405392cc8c0f5cULL;
};

template<class ContainerAllocator>
struct DataType< ::encoder_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "encoder_msgs/Encoder";
  }

  static const char* value(const ::encoder_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::encoder_msgs::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 time_stamp\n\
int64 left_encoder_count\n\
int64 right_encoder_count\n\
";
  }

  static const char* value(const ::encoder_msgs::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::encoder_msgs::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_stamp);
      stream.next(m.left_encoder_count);
      stream.next(m.right_encoder_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::encoder_msgs::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::encoder_msgs::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "time_stamp: ";
    Printer<float>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "left_encoder_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left_encoder_count);
    s << indent << "right_encoder_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right_encoder_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENCODER_MSGS_MESSAGE_ENCODER_H
